In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, Flatten

In [2]:
#The data used is chrun data, where data has category and number, so it is processed first

In [3]:
data=pd.read_excel("churndata.xlsx")

In [4]:
print(data)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMemb

In [5]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [8]:
data.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [9]:
file=pd.read_csv("dataset.csv")

In [10]:
#The data used is then converted to number form, namely Geography and Gender variables

In [11]:
file=pd.read_csv("dataset.csv")

In [12]:
print(file)

      CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0       0   42       2       0.00              1   
1             608          2       0   41       1   83807.86              1   
2             502          0       0   42       8  159660.80              3   
3             699          0       0   39       1       0.00              2   
4             850          2       0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0       1   39       5       0.00              2   
9996          516          0       1   35      10   57369.61              1   
9997          709          0       0   36       7       0.00              1   
9998          772          1       1   42       3   75075.31              2   
9999          792          0       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  E

In [13]:
file.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [14]:
x=file.iloc[:,0:9].values
y=file.iloc[:,-1].values

In [15]:
print(x)

[[619.   0.   0. ...   1.   1.   1.]
 [608.   2.   0. ...   1.   0.   1.]
 [502.   0.   0. ...   3.   1.   0.]
 ...
 [709.   0.   0. ...   1.   0.   1.]
 [772.   1.   1. ...   2.   1.   0.]
 [792.   0.   0. ...   1.   1.   0.]]


In [16]:
print(y)

[1 0 1 ... 1 1 0]


In [25]:
import numpy as np
import pandas as pd

from matplotlib import pyplot as plt

from sklearn.model_selection import train_test_split

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import load_model

In [26]:
print(tf.__version__)

1.15.0


In [27]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 1234)

In [41]:
input_dim=X_train.shape[1]

In [42]:
print(input_dim)

9


In [28]:
# column order in CSV file
column_names = ['CreditScore','Geography','Gender''Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary','Exited']

feature_names = column_names[:-1]
label_name = column_names[-1]

print("Features: {}".format(feature_names))
print("Label: {}".format(label_name))

Features: ['CreditScore', 'Geography', 'GenderAge', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']
Label: Exited


In [29]:
# Create an Artificial Neural Network model
# JST models that are made using a hard framework with specifications:

# 2 hidden layers with 10 neurons and 10 neurons
#neuron uses the ReLU activation function
#and the output layer with the sigmoid activation function

In [30]:
model = Sequential()
model.add(Dense(10, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [31]:
model.summary

<bound method Network.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x0000000016AC8688>>

In [36]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [37]:
#do learning

In [38]:
model.fit(X_train, y_train, epochs=150, batch_size=10000)

Train on 8000 samples
Epoch 1/150
8000/8000 [==============================] - 0s 12us/sample - loss: 8682.1064 - acc: 0.7969
Epoch 2/150
8000/8000 [==============================] - 0s 1us/sample - loss: 8513.3945 - acc: 0.7969
Epoch 3/150
8000/8000 [==============================] - 0s 2us/sample - loss: 8345.5664 - acc: 0.7969
Epoch 4/150
8000/8000 [==============================] - 0s 1us/sample - loss: 8178.6387 - acc: 0.7969
Epoch 5/150
8000/8000 [==============================] - 0s 1us/sample - loss: 8012.6211 - acc: 0.7969
Epoch 6/150
8000/8000 [==============================] - 0s 1us/sample - loss: 7847.5220 - acc: 0.7969
Epoch 7/150
8000/8000 [==============================] - 0s 1us/sample - loss: 7683.3374 - acc: 0.7969
Epoch 8/150
8000/8000 [==============================] - 0s 1us/sample - loss: 7520.0537 - acc: 0.7969
Epoch 9/150
8000/8000 [==============================] - 0s 1us/sample - loss: 7357.5273 - acc: 0.7969
Epoch 10/150
8000/8000 [==========================

Epoch 80/150
8000/8000 [==============================] - 0s 1us/sample - loss: 152.1964 - acc: 0.2027
Epoch 81/150
8000/8000 [==============================] - 0s 1us/sample - loss: 14.3920 - acc: 0.3719
Epoch 82/150
8000/8000 [==============================] - 0s 1us/sample - loss: 62.9726 - acc: 0.5370
Epoch 83/150
8000/8000 [==============================] - 0s 1us/sample - loss: 102.9854 - acc: 0.5370
Epoch 84/150
8000/8000 [==============================] - 0s 1us/sample - loss: 128.4849 - acc: 0.5370
Epoch 85/150
8000/8000 [==============================] - 0s 1us/sample - loss: 140.8732 - acc: 0.5370
Epoch 86/150
8000/8000 [==============================] - 0s 1us/sample - loss: 141.4087 - acc: 0.5370
Epoch 87/150
8000/8000 [==============================] - 0s 1us/sample - loss: 131.2191 - acc: 0.5370
Epoch 88/150
8000/8000 [==============================] - 0s 0us/sample - loss: 111.3171 - acc: 0.5370
Epoch 89/150
8000/8000 [==============================] - 0s 1us/sample - l

In [39]:
accuracy = model.evaluate(X_test, y_test)

2000/2000 [==============================] - 0s 36us/sample - loss: 23.9111 - acc: 0.2700


In [40]:
model.save('my_model.h5')

In [ ]:
#Bibliography website 
#"http://keshans.com/Churn_prediction-on-tensorflow/"
#https://www.tensorflow.org/tutorials/customization/custom_training_walkthrough
#https://keras.io/getting-started/sequential-model-guide/

In [43]:
model = Sequential()
model.add(Dense(16, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [44]:
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [45]:
model.fit(X_train, y_train, epochs=200, batch_size=8000)

Train on 8000 samples
Epoch 1/200
8000/8000 [==============================] - 0s 12us/sample - loss: 4899.2764 - acc: 0.7969
Epoch 2/200
8000/8000 [==============================] - 0s 1us/sample - loss: 4567.0547 - acc: 0.7969
Epoch 3/200
8000/8000 [==============================] - 0s 1us/sample - loss: 4361.8398 - acc: 0.7969
Epoch 4/200
8000/8000 [==============================] - 0s 1us/sample - loss: 4197.8140 - acc: 0.7969
Epoch 5/200
8000/8000 [==============================] - 0s 1us/sample - loss: 4055.2883 - acc: 0.7969
Epoch 6/200
8000/8000 [==============================] - 0s 1us/sample - loss: 3926.7825 - acc: 0.7969
Epoch 7/200
8000/8000 [==============================] - 0s 1us/sample - loss: 3808.3235 - acc: 0.7969
Epoch 8/200
8000/8000 [==============================] - 0s 1us/sample - loss: 3697.4651 - acc: 0.7969
Epoch 9/200
8000/8000 [==============================] - 0s 1us/sample - loss: 3592.5657 - acc: 0.7969
Epoch 10/200
8000/8000 [==========================

Epoch 80/200
8000/8000 [==============================] - 0s 1us/sample - loss: 630.9449 - acc: 0.7952
Epoch 81/200
8000/8000 [==============================] - 0s 1us/sample - loss: 604.1605 - acc: 0.7969
Epoch 82/200
8000/8000 [==============================] - 0s 1us/sample - loss: 577.2410 - acc: 0.7959
Epoch 83/200
8000/8000 [==============================] - 0s 1us/sample - loss: 550.2582 - acc: 0.7969
Epoch 84/200
8000/8000 [==============================] - 0s 1us/sample - loss: 523.5543 - acc: 0.7959
Epoch 85/200
8000/8000 [==============================] - 0s 1us/sample - loss: 497.0085 - acc: 0.7969
Epoch 86/200
8000/8000 [==============================] - 0s 1us/sample - loss: 469.6288 - acc: 0.7959
Epoch 87/200
8000/8000 [==============================] - 0s 1us/sample - loss: 442.1800 - acc: 0.7969
Epoch 88/200
8000/8000 [==============================] - 0s 1us/sample - loss: 414.6078 - acc: 0.7962
Epoch 89/200
8000/8000 [==============================] - 0s 1us/sample -

Epoch 160/200
8000/8000 [==============================] - 0s 1us/sample - loss: 33.6965 - acc: 0.7969
Epoch 161/200
8000/8000 [==============================] - 0s 1us/sample - loss: 18.3271 - acc: 0.7970
Epoch 162/200
8000/8000 [==============================] - 0s 1us/sample - loss: 2.4534 - acc: 0.7944
Epoch 163/200
8000/8000 [==============================] - 0s 1us/sample - loss: 42.1554 - acc: 0.4625
Epoch 164/200
8000/8000 [==============================] - 0s 1us/sample - loss: 34.1419 - acc: 0.7969
Epoch 165/200
8000/8000 [==============================] - 0s 1us/sample - loss: 18.7568 - acc: 0.7970
Epoch 166/200
8000/8000 [==============================] - 0s 1us/sample - loss: 2.8684 - acc: 0.7968
Epoch 167/200
8000/8000 [==============================] - 0s 1us/sample - loss: 43.6423 - acc: 0.4627
Epoch 168/200
8000/8000 [==============================] - 0s 1us/sample - loss: 33.5651 - acc: 0.7969
Epoch 169/200
8000/8000 [==============================] - 0s 1us/sample - 

In [46]:
accuracy = model.evaluate(X_test, y_test)

2000/2000 [==============================] - 0s 33us/sample - loss: 19.3246 - acc: 0.7940


In [47]:
model.save('my_model2.h5')